# Generated by Django 5.2.5 on 2025-09-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='fictional',
            field=models.BooleanField(default=False, verbose_name='fictional'),
        ),
    ]
