# Generated by Django 5.2.5 on 2025-09-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_placetype_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='plural',
            field=models.CharField(default='Uknown Plural', max_length=255, unique=True, verbose_name='plural'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placetype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
