# Generated by Django 5.2.5 on 2025-09-02 21:13

import django.db.models.deletion
from django.db import migrations, models

## Before running, all places need to be manually assigned a type

class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_placetype_plural_alter_placetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.placetype'),
        ),
    ]
