# Generated by Django 5.2.5 on 2025-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_alter_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('order', models.IntegerField(unique=True, verbose_name='order')),
            ],
            options={
                'verbose_name': 'day of the week',
                'verbose_name_plural': 'days of the week',
            },
        ),
    ]
