# Generated by Django 5.2.5 on 2025-09-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_dayofweek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'verbose_name': 'Day of the Week', 'verbose_name_plural': 'Days of the Week'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='placetype',
            options={'verbose_name': 'Place Type', 'verbose_name_plural': 'Place Types'},
        ),
    ]
