# Generated by Django 5.2.5 on 2025-09-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_alter_dayofweek_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('order_in_calendar', models.IntegerField(verbose_name='order in calendar')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.calendar')),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
                'ordering': ['calendar', 'order_in_calendar'],
                'unique_together': {('calendar', 'name'), ('calendar', 'order_in_calendar')},
            },
        ),
    ]
