# Generated by Django 5.2.5 on 2025-09-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_festival'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['name'], 'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendars'},
        ),
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'ordering': ['order'], 'verbose_name': 'Day of the Week', 'verbose_name_plural': 'Days of the Week'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='placetype',
            options={'ordering': ['name'], 'verbose_name': 'Place Type', 'verbose_name_plural': 'Place Types'},
        ),
    ]
