# Generated by Django 5.2.5 on 2025-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_alter_calendar_options_alter_dayofweek_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('year', models.IntegerField(blank=True, help_text='Approximate year of the memory', null=True, verbose_name='year')),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
                'ordering': ['year', 'name'],
            },
        ),
    ]
