# Generated by Django 5.2.5 on 2025-09-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate value of this number, up to 2 decimal places', max_digits=32, null=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Number',
                'verbose_name_plural': 'Numbers',
                'ordering': ['value', 'name'],
            },
        ),
    ]
