# Generated by Django 5.2.6 on 2025-09-11 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_transportmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageFamily',
            fields=[
                ('code', models.CharField(help_text='A valid ISO 639-5 code', max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Language Family',
                'verbose_name_plural': 'Language Families',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(help_text='A valid ISO 639-3 code', max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.languagefamily')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['code'],
            },
        ),
    ]
