# Generated by Django 5.2.7 on 2025-10-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_languagefamily_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('wikipedia_slug', models.CharField(help_text='The URL Slug used by the primary page regarding this event on the English Language instance of Wikipedia', max_length=255, unique=True, verbose_name='Wikipedia URL Slug')),
                ('year', models.IntegerField(blank=True, help_text='Approximate year of the event, in the Gregorian Calendar', null=True, verbose_name='year')),
            ],
            options={
                'verbose_name': 'Historical Event',
                'verbose_name_plural': 'Historical Events',
                'ordering': ['year', 'name'],
            },
        ),
    ]
