# Generated by Django 5.2.7 on 2025-10-06 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_historicalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagefamily',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='metadata.languagefamily'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text='A valid ISO 639 code', max_length=15, primary_key=True, serialize=False, verbose_name='code'),
        ),
    ]
