# Generated by Django 5.2.7 on 2025-10-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0016_languagefamily_parent_alter_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weathers',
                'ordering': ['name'],
            },
        ),
    ]
