# Generated by Django 5.2.7 on 2025-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0017_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthnicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Ethnic Group',
                'verbose_name_plural': 'Ethnic Groups',
                'ordering': ['name'],
            },
        ),
    ]
