# Generated by Django 5.2.7 on 2025-10-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0019_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['name'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
    ]
