# Generated by Django 5.2.7 on 2025-10-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0020_alter_season_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['pk'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
    ]
