# Generated by Django 5.2.7 on 2025-11-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0021_alter_season_options'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='calendar',
            table_comment='A system for organizing dates.',
        ),
        migrations.AlterModelTableComment(
            name='festival',
            table_comment='A recurring celebration or event.',
        ),
        migrations.AlterModelTableComment(
            name='historicalevent',
            table_comment='A notable thing that happened in the past.',
        ),
        migrations.AlterModelTableComment(
            name='memory',
            table_comment='A remembered event or fact.',
        ),
        migrations.AlterModelTableComment(
            name='number',
            table_comment='A numeric concept.',
        ),
        migrations.AlterModelTableComment(
            name='weather',
            table_comment='A short term state of the atmosphere.',
        ),
    ]
