# Generated by Django 5.2.8 on 2025-11-07 03:03

import django.db.models.deletion
import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0022_alter_calendar_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='order',
            field=lucos_eolas.metadata.fields.RDFIntegerField(unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(help_text='The URL Slug used by the primary page regarding this event on the English Language instance of Wikipedia', max_length=255, unique=True, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='year',
            field=lucos_eolas.metadata.fields.RDFYearField(blank=True, help_text='Approximate year of the event, in the Gregorian Calendar', null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=lucos_eolas.metadata.fields.RDFCharField(help_text='A valid ISO 639 code', max_length=15, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='language',
            name='family',
            field=lucos_eolas.metadata.fields.RDFForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.languagefamily'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='languagefamily',
            name='code',
            field=lucos_eolas.metadata.fields.RDFCharField(help_text='A valid ISO 639-5 code', max_length=3, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='languagefamily',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='languagefamily',
            name='parent',
            field=lucos_eolas.metadata.fields.RDFForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='metadata.languagefamily'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='description',
            field=lucos_eolas.metadata.fields.RDFTextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='year',
            field=lucos_eolas.metadata.fields.RDFYearField(blank=True, help_text='Approximate year of the memory', null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='month',
            name='calendar',
            field=lucos_eolas.metadata.fields.RDFForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.calendar'),
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='month',
            name='order_in_calendar',
            field=lucos_eolas.metadata.fields.RDFIntegerField(verbose_name='order in calendar'),
        ),
        migrations.AlterField(
            model_name='number',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='number',
            name='value',
            field=lucos_eolas.metadata.fields.RDFDecimalField(blank=True, decimal_places=2, help_text='Approximate value of this number, up to 2 decimal places', max_digits=32, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=lucos_eolas.metadata.fields.RDFForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.placetype'),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='plural',
            field=lucos_eolas.metadata.fields.RDFCharField(max_length=255, unique=True, verbose_name='plural'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='transportmode',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'),
        ),
    ]
