# Generated by Django 5.2.8 on 2025-11-09 21:10

import django.db.models.deletion
import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0023_alter_calendar_name_alter_dayofweek_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='place',
            table_comment='Entities that have a somewhat fixed, physical extension.',
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='order',
            field=lucos_eolas.metadata.fields.RDFIntegerField(db_comment='Order of day in the week.', unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='day_of_month',
            field=models.IntegerField(blank=True, db_comment='When a festival starts.', null=True, verbose_name='day of month'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='month',
            field=models.ForeignKey(blank=True, db_comment='When a festival starts.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='metadata.month'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='year',
            field=lucos_eolas.metadata.fields.RDFYearField(blank=True, db_comment='The approximate point in time an event occured', help_text='Approximate year of the event, in the Gregorian Calendar', null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='year',
            field=lucos_eolas.metadata.fields.RDFYearField(blank=True, db_comment='The point in time a memory is recalling.', help_text='Approximate year of the memory', null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='month',
            name='calendar',
            field=lucos_eolas.metadata.fields.RDFForeignKey(db_comment='Calendar this month belongs to.', on_delete=django.db.models.deletion.RESTRICT, to='metadata.calendar'),
        ),
        migrations.AlterField(
            model_name='month',
            name='order_in_calendar',
            field=lucos_eolas.metadata.fields.RDFIntegerField(db_comment='Order of month in calendar.', verbose_name='order in calendar'),
        ),
        migrations.AlterField(
            model_name='number',
            name='value',
            field=lucos_eolas.metadata.fields.RDFDecimalField(blank=True, db_comment='The (approximate) numeric value for a number.', decimal_places=2, help_text='Approximate value of this number, up to 2 decimal places', max_digits=32, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='place',
            name='fictional',
            field=lucos_eolas.metadata.fields.RDFBooleanField(db_comment='Whether or not a place is fictional.', default=False, verbose_name='fictional'),
        ),
    ]
