# Generated by Django 5.2.8 on 2025-11-17 20:28

import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0024_alter_place_table_comment_alter_dayofweek_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'db_table_comment': 'The geographic location of a place relative to others',
                'ordering': ['name'],
            },
        ),
    ]
