# Generated by Django 5.2.8 on 2025-11-17 21:13

import django.db.models.deletion
import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0025_direction'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='direction',
            table_comment='The geographic location of a self relative to others',
        ),
        migrations.AlterField(
            model_name='festival',
            name='day_of_month',
            field=models.IntegerField(blank=True, db_comment='When a self starts.', null=True, verbose_name='day of month'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='month',
            field=models.ForeignKey(blank=True, db_comment='When a self starts.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='metadata.month'),
        ),
        migrations.AlterField(
            model_name='place',
            name='fictional',
            field=lucos_eolas.metadata.fields.RDFBooleanField(db_comment='Whether or not a self is fictional.', default=False, verbose_name='fictional'),
        ),
    ]
