# Generated by Django 5.2.8 on 2025-11-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0026_alter_direction_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='metonym',
            field=models.CharField(blank=True, help_text='Something this place is often used as a substitue for', max_length=255, verbose_name='metonym'),
        ),
    ]
