# Generated by Django 5.2.8 on 2025-11-19 21:01

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0027_place_metonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='direction',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='festival',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='language',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='languagefamily',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='memory',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='month',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='number',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='place',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='placetype',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='season',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='transportmode',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wikipedia_slug',
            field=lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug'),
        ),
    ]
