# Generated by Django 5.2.8 on 2025-11-19 21:07

import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0028_calendar_wikipedia_slug_dayofweek_wikipedia_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name')),
                ('wikipedia_slug', lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table_comment': 'A group of people with a particular shared purpose',
                'ordering': ['name'],
            },
        ),
    ]
