# Generated by Django 5.2.8 on 2025-11-29 13:28

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0029_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='fictional',
            field=lucos_eolas.metadata.fields.RDFBooleanField(db_comment='Whether or not a place is fictional.', default=False, verbose_name='fictional'),
        ),
        migrations.AlterField(
            model_name='place',
            name='located_in',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, related_name='contains', to='metadata.place', verbose_name='located in'),
        ),
    ]
