# Generated by Django 6.0 on 2025-12-27 13:57

import django.db.models.deletion
import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0030_alter_place_fictional_alter_place_located_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='commemorates',
            field=lucos_eolas.metadata.fields.RDFForeignKey(blank=True, db_comment='Historical event this festival commemorates', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.historicalevent'),
        ),
    ]
