# Generated by Django 6.0 on 2026-01-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0032_auto_20251227_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='category',
            field=models.CharField(choices=[('People', 'People'), ('Anthropological', 'Anthropological'), ('Anthropogeographical', 'Anthropogeographical'), ('Musical', 'Musical'), ('Aquatic', 'Aquatic'), ('Terrestrial', 'Terrestrial'), ('Cosmic', 'Cosmic'), ('Supernatural', 'Supernatural'), ('Historical', 'Historical'), ('Temporal', 'Temporal'), ('Mathematical', 'Mathematical'), ('Technological', 'Technological'), ('Meteorological', 'Meteorological')], default='Terrestrial', verbose_name='category'),
            preserve_default=False,
        ),
    ]
