# Generated by Django 6.0 on 2026-01-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0033_placetype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='category',
            field=models.CharField(choices=[('People', 'People'), ('Anthropological', 'Anthropological'), ('Anthropogeographical', 'Anthropogeographical'), ('Musical', 'Musical'), ('Aquatic', 'Aquatic'), ('Terrestrial', 'Terrestrial'), ('Cosmic', 'Cosmic'), ('Supernatural', 'Supernatural'), ('Historical', 'Historical'), ('Temporal', 'Temporal'), ('Mathematical', 'Mathematical'), ('Technological', 'Technological'), ('Meteorological', 'Meteorological'), ('Meta', 'Meta')], verbose_name='category'),
        ),
    ]
