# Generated by Django 6.0.1 on 2026-01-30 20:12

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0034_alter_placetype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
    ]
