# Generated by Django 6.0.1 on 2026-01-30 20:20

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0035_alter_place_alternate_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='direction',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='festival',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='language',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='languagefamily',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='memory',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='month',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='number',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='placetype',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='season',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='transportmode',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
        migrations.AddField(
            model_name='weather',
            name='alternate_names',
            field=lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as'),
        ),
    ]
