# Generated by Django 6.0.1 on 2026-01-31 12:11

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0036_add_alternate_names_to_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalevent',
            old_name='year',
            new_name='start_year',
        ),
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'ordering': ['start_year', 'name'], 'verbose_name': 'Historical Event', 'verbose_name_plural': 'Historical Events'},
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='start_year',
            field=lucos_eolas.metadata.fields.RDFYearField(blank=True, db_comment='The approximate point in time an event began', help_text='Approximate year the event started, in the Gregorian Calendar', null=True, verbose_name='start year'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='end_year',
            field=lucos_eolas.metadata.fields.RDFYearField(blank=True, db_comment='The approximate point in time an event finished', help_text='Approximate year the event ended, in the Gregorian Calendar', null=True, verbose_name='end year'),
        ),
    ]
