# Generated by Django 6.0.1 on 2026-02-06 14:38

import django.db.models.deletion
import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0037_alter_historicalevent_split_year_into_start_and_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name')),
                ('alternate_names', lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as')),
                ('wikipedia_slug', lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug')),
                ('plural', lucos_eolas.metadata.fields.RDFCharField(max_length=255, unique=True, verbose_name='plural')),
                ('category', models.CharField(choices=[('People', 'People'), ('Anthropological', 'Anthropological'), ('Anthropogeographical', 'Anthropogeographical'), ('Musical', 'Musical'), ('Aquatic', 'Aquatic'), ('Terrestrial', 'Terrestrial'), ('Cosmic', 'Cosmic'), ('Supernatural', 'Supernatural'), ('Historical', 'Historical'), ('Temporal', 'Temporal'), ('Mathematical', 'Mathematical'), ('Technological', 'Technological'), ('Meteorological', 'Meteorological'), ('Meta', 'Meta')], verbose_name='category')),
            ],
            options={
                'verbose_name': 'Creative Work Type',
                'verbose_name_plural': 'Creative Work Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_names', lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as')),
                ('wikipedia_slug', lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name')),
                ('type', lucos_eolas.metadata.fields.RDFForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.creativeworktype')),
            ],
            options={
                'verbose_name': 'Creative Work',
                'verbose_name_plural': 'Creative Works',
                'ordering': ['name'],
            },
        ),
    ]
