# Generated by Django 6.0.1 on 2026-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0038_creativeworktype_creativework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeworktype',
            name='category',
            field=models.CharField(choices=[('People', 'People'), ('Anthropological', 'Anthropological'), ('Anthropogeographical', 'Anthropogeographical'), ('Musical', 'Musical'), ('Aquatic', 'Aquatic'), ('Terrestrial', 'Terrestrial'), ('Cosmic', 'Cosmic'), ('Supernatural', 'Supernatural'), ('Historical', 'Historical'), ('Temporal', 'Temporal'), ('Mathematical', 'Mathematical'), ('Technological', 'Technological'), ('Meteorological', 'Meteorological'), ('Meta', 'Meta'), ('Dramaturgical', 'Dramaturgical'), ('Literary', 'Literary')], verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='category',
            field=models.CharField(choices=[('People', 'People'), ('Anthropological', 'Anthropological'), ('Anthropogeographical', 'Anthropogeographical'), ('Musical', 'Musical'), ('Aquatic', 'Aquatic'), ('Terrestrial', 'Terrestrial'), ('Cosmic', 'Cosmic'), ('Supernatural', 'Supernatural'), ('Historical', 'Historical'), ('Temporal', 'Temporal'), ('Mathematical', 'Mathematical'), ('Technological', 'Technological'), ('Meteorological', 'Meteorological'), ('Meta', 'Meta'), ('Dramaturgical', 'Dramaturgical'), ('Literary', 'Literary')], verbose_name='category'),
        ),
    ]
