# Generated by Django 6.0.2 on 2026-02-22 00:49

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0039_alter_creativeworktype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethnicgroup',
            name='heritage_language',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, db_comment='The traditional or heritage language of this ethnic group.', related_name='heritage_groups', to='metadata.language', verbose_name='heritage language'),
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='indigenous_to',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, db_comment='Places where this ethnic group originated or is endemic to.', related_name='indigenous_groups', to='metadata.place', verbose_name='indigenous to'),
        ),
        migrations.AddField(
            model_name='language',
            name='indigenous_to',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, db_comment='Places where this language originated or is endemic to.', related_name='indigenous_languages', to='metadata.place', verbose_name='indigenous to'),
        ),
        migrations.AddField(
            model_name='language',
            name='widely_spoken_in',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, db_comment='Places where this language is currently widely spoken.', related_name='widely_spoken_languages', to='metadata.place', verbose_name='widely spoken in'),
        ),
    ]
