# Generated by Django 6.0.2 on 2026-02-22 00:58

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0040_ethnicgroup_heritage_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethnicgroup',
            name='heritage_language',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, related_name='heritage_groups', to='metadata.language', verbose_name='heritage language'),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='indigenous_to',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, related_name='indigenous_groups', to='metadata.place', verbose_name='indigenous to'),
        ),
        migrations.AlterField(
            model_name='language',
            name='indigenous_to',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, related_name='indigenous_languages', to='metadata.place', verbose_name='indigenous to'),
        ),
        migrations.AlterField(
            model_name='language',
            name='widely_spoken_in',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, related_name='widely_spoken_languages', to='metadata.place', verbose_name='widely spoken in'),
        ),
    ]
