# Generated by Django 6.0.2 on 2026-02-22 01:23

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0041_alter_ethnicgroup_heritage_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='located_in',
            new_name='contained_in',
        ),
        migrations.AddField(
            model_name='place',
            name='bounds',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, related_name='bounded_by', to='metadata.place', verbose_name='bounds'),
        ),
        migrations.AlterField(
            model_name='place',
            name='contained_in',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, related_name='contains', to='metadata.place', verbose_name='contained in'),
        ),
        migrations.AddField(
            model_name='place',
            name='partially_contained_in',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, related_name='partially_contains', to='metadata.place', verbose_name='partially contained in'),
        ),
        migrations.AddField(
            model_name='place',
            name='territory_of',
            field=lucos_eolas.metadata.fields.RDFManyToManyField(blank=True, related_name='has_territory', to='metadata.place', verbose_name='territory of'),
        ),
    ]
