# Generated by Django 6.0.4 on 2026-05-01 00:19

import django.db.models.deletion
import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0042_remove_place_located_in_place_bounds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_names', lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as')),
                ('wikipedia_slug', lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name')),
                ('start_day', lucos_eolas.metadata.fields.RDFIntegerField(blank=True, db_comment='Day of month this period starts.', null=True, verbose_name='start day')),
                ('duration_days', lucos_eolas.metadata.fields.RDFIntegerField(blank=True, db_comment='Number of days this period lasts. Null means one day (if start_day set) or the entire month (if only start_month set).', null=True, verbose_name='duration (days)')),
                ('festival', lucos_eolas.metadata.fields.RDFForeignKey(db_comment='Festival this period belongs to.', on_delete=django.db.models.deletion.CASCADE, to='metadata.festival')),
                ('start_month', lucos_eolas.metadata.fields.RDFForeignKey(blank=True, db_comment='Month this period starts in.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='festival_periods', to='metadata.month')),
            ],
            options={
                'verbose_name': 'Festival Period',
                'verbose_name_plural': 'Festival Periods',
                'db_table_comment': 'A temporal period associated with a festival.',
                'ordering': ['festival', 'start_month', 'start_day'],
            },
        ),
    ]
