# Generated by Django 6.0.4 on 2026-05-01 10:26

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0044_populate_festival_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='temporal_id',
            field=lucos_eolas.metadata.fields.RDFCharField(blank=True, db_comment='TC39 Temporal calendar identifier for this calendar system.', help_text='The calendar identifier used by the TC39 Temporal API (e.g. "gregory", "hebrew", "islamic", "chinese", "indian").', max_length=20, null=True, verbose_name='Temporal calendar ID'),
        ),
        migrations.AddField(
            model_name='month',
            name='temporal_month_code',
            field=lucos_eolas.metadata.fields.RDFCharField(blank=True, db_comment='TC39 Temporal monthCode for this month (stable across leap years).', help_text='The stable month code used by the TC39 Temporal API (e.g. "M01", "M07", "M06L" for Adar II). Stable across leap/non-leap years.', max_length=4, null=True, verbose_name='Temporal month code'),
        ),
    ]
