# Generated by Django 6.0.4 on 2026-05-04 23:00

import django.db.models.deletion
import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0046_populate_temporal_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='day_of_month',
            field=models.IntegerField(blank=True, db_comment="Day of the month of the festival's defining day.", help_text="The day of the month on which the festival's defining day falls.", null=True, verbose_name='day of month'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='month',
            field=models.ForeignKey(blank=True, db_comment="Month of the festival's defining day.", help_text="The month in which the festival's defining day falls.", null=True, on_delete=django.db.models.deletion.RESTRICT, to='metadata.month', verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='festivalperiod',
            name='duration_days',
            field=lucos_eolas.metadata.fields.RDFIntegerField(blank=True, db_comment='Number of days this period lasts. Null means one day (if start_day set) or the entire start_month (if start_day null).', help_text='Length of this period in days. Leave blank for a single day or a whole month.', null=True, verbose_name='duration (days)'),
        ),
        migrations.AlterField(
            model_name='festivalperiod',
            name='start_day',
            field=lucos_eolas.metadata.fields.RDFIntegerField(blank=True, db_comment='Day of month this period starts.', help_text='Day of the month on which this period begins. Leave blank for a whole-month period.', null=True, verbose_name='start day'),
        ),
        migrations.AlterField(
            model_name='festivalperiod',
            name='start_month',
            field=lucos_eolas.metadata.fields.RDFForeignKey(blank=True, db_comment='Month this period starts in.', help_text='The month in which this period begins.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='festival_periods', to='metadata.month', verbose_name='start month'),
        ),
    ]
