# Generated by Django 6.0.5 on 2026-05-08 00:27
# Manually adjusted: plural added as nullable to allow backfill before unique constraint is applied.

import django.db.models.deletion
import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0047_alter_festival_day_of_month_alter_festival_month_and_more'),
    ]

    operations = [
        # Add plural as nullable first — allows the data migration (0049) to
        # backfill actual values before the unique constraint is applied (0050).
        # Adding it as unique=True with a default would conflict on existing rows
        # (all 24 rows would get the same default, violating the unique constraint).
        migrations.AddField(
            model_name='transportmode',
            name='plural',
            field=lucos_eolas.metadata.fields.RDFCharField(blank=True, max_length=255, null=True, verbose_name='plural'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_names', lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as')),
                ('wikipedia_slug', lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=False, verbose_name='name')),
                ('fictional', lucos_eolas.metadata.fields.RDFBooleanField(db_comment='Whether or not a vehicle is fictional.', default=False, verbose_name='fictional')),
                ('type', lucos_eolas.metadata.fields.RDFForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.transportmode')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['name'],
            },
        ),
    ]
