# Generated by Django 6.0.5 on 2026-05-08 00:36

import lucos_eolas.metadata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0050_alter_transportmode_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='festivalperiod',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=False, verbose_name='name'),
        ),
    ]
