# Generated by Django 6.0.5 on 2026-05-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0051_alter_creativework_name_alter_festivalperiod_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='languagefamily',
            options={'ordering': ['name'], 'verbose_name': 'Language Family', 'verbose_name_plural': 'Language Families'},
        ),
    ]
