# Generated by Django 6.0.5 on 2026-05-17 22:00

import django.db.models.deletion
import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0052_alter_language_options_alter_languagefamily_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name')),
                ('alternate_names', lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as')),
                ('wikipedia_slug', lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug')),
                ('plural', lucos_eolas.metadata.fields.RDFCharField(max_length=255, unique=True, verbose_name='plural')),
                ('category', models.CharField(choices=[('People', 'People'), ('Anthropological', 'Anthropological'), ('Anthropogeographical', 'Anthropogeographical'), ('Musical', 'Musical'), ('Aquatic', 'Aquatic'), ('Terrestrial', 'Terrestrial'), ('Cosmic', 'Cosmic'), ('Supernatural', 'Supernatural'), ('Historical', 'Historical'), ('Temporal', 'Temporal'), ('Mathematical', 'Mathematical'), ('Technological', 'Technological'), ('Meteorological', 'Meteorological'), ('Meta', 'Meta'), ('Dramaturgical', 'Dramaturgical'), ('Literary', 'Literary')], verbose_name='category')),
            ],
            options={
                'verbose_name': 'Person Type',
                'verbose_name_plural': 'Person Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_names', lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as')),
                ('wikipedia_slug', lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=False, verbose_name='name')),
                ('is_fictional', lucos_eolas.metadata.fields.RDFBooleanField(db_comment='Whether or not a person is fictional.', default=False, verbose_name='fictional')),
                ('type', lucos_eolas.metadata.fields.RDFForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.persontype')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table_comment': 'A famous, fictional, or named-but-not-personal person.',
                'ordering': ['name'],
            },
        ),
    ]
