# Generated by Django 6.0.5 on 2026-05-18 00:43

import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0052_alter_language_options_alter_languagefamily_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_names', lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as')),
                ('wikipedia_slug', lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=False, verbose_name='name')),
                ('fictional', lucos_eolas.metadata.fields.RDFBooleanField(db_comment='Whether or not a person is fictional.', default=False, verbose_name='fictional')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table_comment': 'An individual human being.',
                'ordering': ['name'],
            },
        ),
    ]
