# Generated by Django 6.0.5 on 2026-05-28 15:31

import lucos_eolas.metadata.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0053_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name')),
                ('alternate_names', lucos_eolas.metadata.fields.RDFArrayField(base_field=lucos_eolas.metadata.fields.RDFNameField(max_length=255, unique=True, verbose_name='name'), blank=True, default=list, help_text='Enter alternate names separated by commas.', verbose_name='also known as')),
                ('wikipedia_slug', lucos_eolas.metadata.fields.WikipediaField(blank=True, help_text='The URL Slug used by the primary page regarding this item on the English Language instance of Wikipedia', max_length=255, verbose_name='Wikipedia URL Slug')),
            ],
            options={
                'verbose_name': 'Offence',
                'verbose_name_plural': 'Offences',
                'db_table_comment': 'A type of potentially offensive or sensitive content that may appear in media.',
                'ordering': ['name'],
            },
        ),
    ]
