# Generated by Django 6.0.5 on 2026-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0055_populate_offences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeworktype',
            name='category',
            field=models.CharField(choices=[('People', 'People'), ('Anthropological', 'Anthropological'), ('Advisory', 'Advisory'), ('Anthropogeographical', 'Anthropogeographical'), ('Musical', 'Musical'), ('Aquatic', 'Aquatic'), ('Terrestrial', 'Terrestrial'), ('Cosmic', 'Cosmic'), ('Supernatural', 'Supernatural'), ('Historical', 'Historical'), ('Temporal', 'Temporal'), ('Mathematical', 'Mathematical'), ('Technological', 'Technological'), ('Meteorological', 'Meteorological'), ('Meta', 'Meta'), ('Dramaturgical', 'Dramaturgical'), ('Literary', 'Literary')], verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='category',
            field=models.CharField(choices=[('People', 'People'), ('Anthropological', 'Anthropological'), ('Advisory', 'Advisory'), ('Anthropogeographical', 'Anthropogeographical'), ('Musical', 'Musical'), ('Aquatic', 'Aquatic'), ('Terrestrial', 'Terrestrial'), ('Cosmic', 'Cosmic'), ('Supernatural', 'Supernatural'), ('Historical', 'Historical'), ('Temporal', 'Temporal'), ('Mathematical', 'Mathematical'), ('Technological', 'Technological'), ('Meteorological', 'Meteorological'), ('Meta', 'Meta'), ('Dramaturgical', 'Dramaturgical'), ('Literary', 'Literary')], verbose_name='category'),
        ),
    ]
